### ISSUE TITLE
how to start this whole thing?

### ISSUE THREAD

**Issue by altsheets** [altsheets/hz-explorer-backend#1]
```
cd hz-explorer-backend/
python nhz_exp.py
```

results in 

```
Traceback (most recent call last):
  File "nhz_exp.py", line 320, in <module>
    main()
  File "nhz_exp.py", line 21, in main
    check = check_fork.validate_block()
  File "/root/hz-blockexplorer/hz-explorer-backend/check_fork.py", line 22, in validate_block
    nextblock = nhz_exp.last_dbblockdata()
  File "/root/hz-blockexplorer/hz-explorer-backend/nhz_exp.py", line 133, in last_dbblockdata
    c.execute("SELECT timestamp, nextblock FROM blockdata ORDER BY timestamp DESC LIMIT 3;")
sqlite3.OperationalError: no such table: blockdata
```

I guess the database has to be created first, and I found the SQL statements in 

```
db.txt
```

but where is the executable/script that creates the database? I guess it will be 

```
 explorer.db
```

right?

**Comment by pharesim** [comment]
sqlite3 explorer.db < db.txt

**Comment by altsheets** [comment]
thx
